### ISSUE TITLE
Error initializing QuantumRenderer: no suitable pipeline found

### ISSUE THREAD

**Issue by samliuk12** [SACHSTech/ICS4U-JavaFXDemo#3]

**Comment by mrfabroa** [comment]
Found [this](https://github.com/javafxports/openjdk-jfx/issues/423), not sure if this applies to you.   Also @samliuk12, what jdk version are you using? 15? Wondering if you go down a version and try

**Comment by samliuk12** [comment]
What I did was download SDK 15 (scroll down, it's under SDK 11 downloads), and it worked

**Comment by mrfabroa** [comment]
If this is on a mac, try reinstalling the appropriate jdk that matches the jfx version.  Also, if you are getting security pop ups, go to System --> privacy and security --> there should be something that references the file that was in the pop up.  You will need to select `allow`.  Try running your code again
