### ISSUE TITLE
Can't find main class

### ISSUE THREAD

**Issue by KyleMendes21** [SACHSTech/ICS4U-JavaFXDemo#4]
Error: Could not find or load main class Mendes.ICS4U.javafx-sdk-11.0.2.lib
Caused by: java.lang.ClassNotFoundException: Mendes.ICS4U.javafx-sdk-11.0.2.lib

**Comment by mrfabroa** [comment]
is your JAVA_HOME environment variable set?  Did you import the reference libraries?

**Comment by KyleMendes21** [comment]
I think the issue might be that my user folder name is "kyle mendes" since it has a space in it. I'm not sure how to fix that. I imported the reference libraries and I set the Java_home environment variables.

**Comment by KyleMendes21** [comment]
when i open up vscode it says this "The JAVA_HOME environment variable (C:\Users\Kyle Mendes\ICS4U\jdk-15.0.1_windows-x64_bin.exe) does not point to a JRE."

**Comment by mrfabroa** [comment]
Check this to see if it resolves it.  It involves working with a shortened path name
https://confluence.atlassian.com/doc/setting-the-java_home-variable-in-windows-8895.html

**Comment by mrfabroa** [comment]
So to create a shortened path name https://manjusullad.wordpress.com/2016/01/06/how-can-i-find-create-short-path-for-windows-folders-directories/  or here https://peoplesofttutorial.com/how-to-create-short-path-for-windows-folders-or-directories/

**Comment by KyleMendes21** [comment]
Apparently my computer already created a short path name for "Kyle Mendes" so I just used that and it worked

**Comment by mrfabroa** [comment]
Terrific!!
