### ISSUE TITLE
"C:\User\<user>" is not recognized as an internal or external command

### ISSUE THREAD

**Issue by CarlosEOL** [SACHSTech/ICS4U-JavaFXDemo#5]
"C:\User\Carlos" is not recognized as an internal or external command,
operable program or batch file.

 "type": "java",
            "name": "Launch Current File",
            "request": "launch",
            "vmArgs": "--module-path /Users/Carlos/.javaFX/javafx-sdk-11.0.2/lib --add-modules javafx.controls,javafx.fxml",
            "mainClass": "${file}"

Everything else stays the same

**Comment by mrfabroa** [comment]
`"vmArgs": "--module-path /Users/Carlos/.javaFX/javafx-sdk-11.0.2/lib --add-modules javafx.controls,javafx.fxml",` should there be a dot in `.javafx`?

**Comment by CarlosEOL** [comment]
Yes, it's the folder's name. Anyhow, I did change it then clone redo the process again

**Comment by CarlosEOL** [comment]
It worked when I change JavaFX files into my hard drive then copied the directory into launch.json.
